apiVersion: v1
metadata:
  name: c29940-i7
baseDomain: edge.statoilfuelretail.com
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 3
compute:
- name: worker
  replicas: 0
  architecture: amd64
  hyperthreading: Enabled
networking:
  clusterNetwork:
  - cidr: 172.30.64.0/18
    hostPrefix: 23
  networkType: OVNKubernetes
  machineNetwork:
  - cidr: 10.206.231.0/24
  serviceNetwork:
  - 172.30.0.0/18
platform:
  baremetal:
    apiVIPs:
    - 10.206.231.80
    ingressVIPs:
    - 10.206.231.81
#bootstrapInPlace:
  #installationDisk: "/dev/nvme0n1"
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfODYxY2VlMWIzZTA5NGM5ZmIyYjJiODQxODRmYzc4ZmE6V1A0VUlZVDVOVFlPMU5HTUpXNkc1TVFBREdOUTc4NU9FVkIxR0xTOTBCVUNCSEY2UjgwTDU1QkROSjdNUThaVw==","email":"marco.anselmo@circlekeurope.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfODYxY2VlMWIzZTA5NGM5ZmIyYjJiODQxODRmYzc4ZmE6V1A0VUlZVDVOVFlPMU5HTUpXNkc1TVFBREdOUTc4NU9FVkIxR0xTOTBCVUNCSEY2UjgwTDU1QkROSjdNUThaVw==","email":"marco.anselmo@circlekeurope.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWVmOWZlZDQ2LWEyNDAtNGRmNy1iMzI5LWIzNjc0MjFhYTc3ZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpNakEwWm1OaFkyWXlOakUwTURZMFlUWmxZV1V6TURkalpUVTVZVGN5TUNKOS5jbnlSSE1kNzY0aHd2VGNuZm5vdllzc1BfeHJhWndpLVRib3BvRHdIT1VMQjNQa05TUmhtT1JsTWRvTC1kMk8wM3ZiVGJ1aTB5b2NJcW1nMVBMM21ObEtzbHB0WHR3MmJjWFhiamphVk8xb1FCc3hZV25lNUU2VVdnbW1XOWs0bDgzQzB4aElfUWZ5azEtUV9lWVZ4WWp5cTV6UmdjbmNWZW1ZbHFsOWZhdGFNanY0cllUOUx1OEE0MUpteXlnTWtqdHFYcnNzU2JYbEs4ZGk0b09mTUplMUVRVElNYlB2c3NKcG9aVk5VbFNkN19KbjE2TU9zd0cyRUdGUjJrdjRkYkUydi01SkdUTUt4dk5SMVdMWmRMWExxaHJ5cjNaOFpXdWtlZUh2ZkFJMVRKcDFFMGxKbERlaDBmeVByRktzTkdsNEF1YWN0djNwU0pHaVlrUlpPX0RicUx5dVloR1R1Y0VGNlFZOFhxbGw0ODkzazNGb04yZEpFQmJDZVRNZi12TTE3QnZFN1JoYzJQVHE1WmRvZ0JUd1I3VzJFYk9nMTZZbWoweS16Uk1oUGxsMFNjcDNNVVJScDlBSHdXbFhDT2FRQnpvTWRPcG8zbUNPakVRSWV6cVFOcTF1MERVZGkzaXVCanE4ckU0YnZXWlpVeW9iVzU2aklIOThoVmFybnd4bGhjRkxXcENNNmNUb2FzeHMzdGg0OTJTd3ZHaXdFNF93SE5MWjJKR1pyZ1lLZzNJZkxBYXhwU0NqdWxsR0RNalEzREFfUGxxcWh4TFM3M2NRY3kwRzZVYmV2ak9ybjlVRTBDbGhiUzViVmQzUjFiSGdUVElQclN3Yy00Q3ZqMWttdDVwS0YyTEo2akFxRFhYQ1hfdGExS0c2ZGJWaFBJQ2ZKeS14a3I1cw==","email":"marco.anselmo@circlekeurope.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWVmOWZlZDQ2LWEyNDAtNGRmNy1iMzI5LWIzNjc0MjFhYTc3ZDpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXpNakEwWm1OaFkyWXlOakUwTURZMFlUWmxZV1V6TURkalpUVTVZVGN5TUNKOS5jbnlSSE1kNzY0aHd2VGNuZm5vdllzc1BfeHJhWndpLVRib3BvRHdIT1VMQjNQa05TUmhtT1JsTWRvTC1kMk8wM3ZiVGJ1aTB5b2NJcW1nMVBMM21ObEtzbHB0WHR3MmJjWFhiamphVk8xb1FCc3hZV25lNUU2VVdnbW1XOWs0bDgzQzB4aElfUWZ5azEtUV9lWVZ4WWp5cTV6UmdjbmNWZW1ZbHFsOWZhdGFNanY0cllUOUx1OEE0MUpteXlnTWtqdHFYcnNzU2JYbEs4ZGk0b09mTUplMUVRVElNYlB2c3NKcG9aVk5VbFNkN19KbjE2TU9zd0cyRUdGUjJrdjRkYkUydi01SkdUTUt4dk5SMVdMWmRMWExxaHJ5cjNaOFpXdWtlZUh2ZkFJMVRKcDFFMGxKbERlaDBmeVByRktzTkdsNEF1YWN0djNwU0pHaVlrUlpPX0RicUx5dVloR1R1Y0VGNlFZOFhxbGw0ODkzazNGb04yZEpFQmJDZVRNZi12TTE3QnZFN1JoYzJQVHE1WmRvZ0JUd1I3VzJFYk9nMTZZbWoweS16Uk1oUGxsMFNjcDNNVVJScDlBSHdXbFhDT2FRQnpvTWRPcG8zbUNPakVRSWV6cVFOcTF1MERVZGkzaXVCanE4ckU0YnZXWlpVeW9iVzU2aklIOThoVmFybnd4bGhjRkxXcENNNmNUb2FzeHMzdGg0OTJTd3ZHaXdFNF93SE5MWjJKR1pyZ1lLZzNJZkxBYXhwU0NqdWxsR0RNalEzREFfUGxxcWh4TFM3M2NRY3kwRzZVYmV2ak9ybjlVRTBDbGhiUzViVmQzUjFiSGdUVElQclN3Yy00Q3ZqMWttdDVwS0YyTEo2akFxRFhYQ1hfdGExS0c2ZGJWaFBJQ2ZKeS14a3I1cw==","email":"marco.anselmo@circlekeurope.com"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEXGhRltP+ApcazuOsCrYBRnxegLLLOAYYHsAjJej45vD6DWXeFsq/v1CrsE9l/HR/9c2y8KzB2bV+iPZnRnbfIiKX9rxeYkyuya4Utpc6zMG48GwAoS6A1MPy11bK20hHpuLVEe+YbJAMXyqPdCtiN/7asGfJhmucBBg8RiVynBhmDoZ921shQ6T0Qm4ay/ZlOom11tSCayAGy59Cdvyzm34dSiPg1xtp1pyPMLcH4r6OpQ4Te3JpNc84VIykZQYFAGQJ/dFnlWmZCYLOITHkfam5m/rD5vRlyLS9w8v4Ryff0YbJIYgpMOLIpC+oQvzhDY4xw2RShRuIjHMoPVjJ marcoanselmo@EDF-PF1KRSPD'
