apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nmstate
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nmstate-operator-group
  namespace: openshift-nmstate
spec:
  targetNamespaces:
    - openshift-nmstate
---
apiVersion: nmstate.io/v1
kind: NMState
metadata:
  name: nmstate
  namespace: openshift-nmstate
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
spec:
  channel: stable
  name: kubernetes-nmstate-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nmstate-static-ip-node1
spec:
  nodeSelector:
    kubernetes.io/hostname: n1
  desiredState:
    interfaces:
      - name: enp3s0f1
        type: ethernet
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 10.255.253.2
              prefix-length: 29
          dhcp: false
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nmstate-static-ip-node2
spec:
  nodeSelector:
    kubernetes.io/hostname: n2
  desiredState:
    interfaces:
      - name: enp3s0f1
        type: ethernet
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 10.255.253.3
              prefix-length: 29
          dhcp: false
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nmstate-static-ip-node3
spec:
  nodeSelector:
    kubernetes.io/hostname: n3
  desiredState:
    interfaces:
      - name: enp3s0f1
        type: ethernet
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 10.255.253.4
              prefix-length: 29
          dhcp: false
