# Create Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nmstate
---
# Create OperatorGroup
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nmstate-operator-group
  namespace: openshift-nmstate
spec:
  targetNamespaces:
    - openshift-nmstate
---
# Create NMState
apiVersion: nmstate.io/v1
kind: NMState
metadata:
  name: nmstate
  namespace: openshift-nmstate
---
# Setup NMState Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kubernetes-nmstate-operator
  namespace: openshift-nmstate
spec:
  channel: stable
  name: kubernetes-nmstate-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
---
# Configure IPs
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: nmstate-static-ip-node1
spec:
  nodeSelector:
    kubernetes.io/hostname: n1
  desiredState:
    interfaces:
      - name: enp3s0f1
        type: ethernet
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 10.255.253.2
              prefix-length: 29
          dhcp: false
---
apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-enp3s0f1-pay
spec:
  desiredState:
    interfaces:
      - bridge:
          options:
            stp:
              enabled: false
          port:
            - name: enp3s0f1
        ipv4:
          dhcp: false
          enabled: false
        name: br-pay
        state: up
        type: linux-bridge
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: external-network
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "br-pay",
      "mode": "bridge",
      "ipam": {}
    }
