apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-enp3s0f1-pay
spec:
  desiredState:
    interfaces:
      - name: enp3s0f1
        type: ethernet
        state: up
        ipv4:
          enabled: false
        ipv6:
          enabled: false
      - name: br-pay
        type: linux-bridge
        state: up
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: enp3s0f1
        ipv4:
          enabled: false
        ipv6:
          enabled: false
---

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: external-network
  namespace: default
spec:
  config: |-
    {
        "cniVersion": "0.3.1",
        "name": "payment-ntw",
        "type": "bridge",
        "bridge": "br-pay",
        "ipam": {},
        "macspoofchk": true,
        "preserveDefaultVlan": false
    }