apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: okta
      openID:
        claims:
          email:
          - email
          name:
          - name
          - email
          preferredUsername:
          - preferred_username
          - email
        clientID: 0oa9wfpnevxv1vSIe0x7
        clientSecret:
          name: openid-okta-secret
        extraScopes:
        - email
        - profile
        issuer: https://circlekeurope.oktapreview.com/oauth2/aus93caqpl9pqZOno0x7                      
      type: OpenID